"""empty message

Revision ID: 424c4a660ce2
Revises: ec05d73f9fde
Create Date: 2018-01-24 11:49:40.095859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424c4a660ce2'
down_revision = 'ec05d73f9fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
